INSERT INTO Diseases (`cat_ID`,`cat_Name`) VALUES(170,'Bệnh văn phòng');
INSERT INTO Diseases (`cat_ID`,`cat_Name`) VALUES(172,'Hô hấp');
INSERT INTO Diseases (`cat_ID`,`cat_Name`) VALUES(175,'Thận - Tiết niệu');
INSERT INTO Diseases (`cat_ID`,`cat_Name`) VALUES(183,'Cơ - Xương - Khớp');
INSERT INTO Diseases (`cat_ID`,`cat_Name`) VALUES(184,'Mắt');
INSERT INTO Diseases (`cat_ID`,`cat_Name`) VALUES(185,'Tai - Mũi - Họng');
INSERT INTO Diseases (`cat_ID`,`cat_Name`) VALUES(186,'Răng - Hàm - Mặt');
INSERT INTO Diseases (`cat_ID`,`cat_Name`) VALUES(188,'Da - Tóc - Da liễu');
INSERT INTO Diseases (`cat_ID`,`cat_Name`) VALUES(189,'Bệnh truyền nhiễm');
INSERT INTO Diseases (`cat_ID`,`cat_Name`) VALUES(190,'Bệnh di truyền');
INSERT INTO Diseases (`cat_ID`,`cat_Name`) VALUES(191,'Huyết học');
INSERT INTO Diseases (`cat_ID`,`cat_Name`) VALUES(192,'Béo phì - Thiếu cân');
INSERT INTO Diseases (`cat_ID`,`cat_Name`) VALUES(193,'Thần kinh - Đau đầu ');
INSERT INTO Diseases (`cat_ID`,`cat_Name`) VALUES(241,'Chuyên đề');
INSERT INTO Diseases (`cat_ID`,`cat_Name`) VALUES(332,'Nội tiết - Tiểu đường');
INSERT INTO Diseases (`cat_ID`,`cat_Name`) VALUES(333,'Huyết áp - Tim mạch');
INSERT INTO Diseases (`cat_ID`,`cat_Name`) VALUES(340,'Bệnh tuổi Teen');
INSERT INTO Diseases (`cat_ID`,`cat_Name`) VALUES(399,'Ngoại khoa');
INSERT INTO Diseases (`cat_ID`,`cat_Name`) VALUES(426,'Dị ứng - Mề đay');
INSERT INTO Diseases (`cat_ID`,`cat_Name`) VALUES(481,'Cấy ghép tạng');
INSERT INTO Diseases (`cat_ID`,`cat_Name`) VALUES(503,'Tụy ');
INSERT INTO Diseases (`cat_ID`,`cat_Name`) VALUES(539,'Tâm lý ');
INSERT INTO Diseases (`cat_ID`,`cat_Name`) VALUES(540,'Bệnh theo mùa');
INSERT INTO Diseases (`cat_ID`,`cat_Name`) VALUES(544,'Sinh sản - Nữ');
INSERT INTO Diseases (`cat_ID`,`cat_Name`) VALUES(545,'Sức khỏe Giới tính');
INSERT INTO Diseases (`cat_ID`,`cat_Name`) VALUES(546,'Sơ cấp cứu ');
INSERT INTO Diseases (`cat_ID`,`cat_Name`) VALUES(641,'Sinh sản - Nam ');
INSERT INTO Diseases (`cat_ID`,`cat_Name`) VALUES(775,'Bệnh tình dục');
INSERT INTO Diseases (`cat_ID`,`cat_Name`) VALUES(781,'Lá lách ');
INSERT INTO Diseases (`cat_ID`,`cat_Name`) VALUES(799,'Lồng ngực - Mạch máu');
INSERT INTO Diseases (`cat_ID`,`cat_Name`) VALUES(817,'Phẫu thuật - Nội soi');
INSERT INTO Diseases (`cat_ID`,`cat_Name`) VALUES(834,'Tiêu hóa - Gan Mật');
INSERT INTO Diseases (`cat_ID`,`cat_Name`) VALUES(839,'Giải độc cơ thể');
